[package]
name = "lacasadelshampoo-pos"
version = "1.0.0"
description = "POS escritorio La Casa del Shampoo"
authors = ["La Casa del Shampoo"]
edition = "2021"

[lib]
name = "lacasadelshampoo_pos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
